{% set name = "ascii_magic" %}
{% set version = "2.7.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ascii_magic-{{ version }}.tar.gz
  sha256: 9ec334fead998dcf469c604bf8c18d3f408c30ab608a340d8fd607a25e074cb8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - colorama
    - pillow
    - python >={{ python_min }}

test:
  imports:
    - ascii_magic
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/LeandroBarone/python-ascii_magic
  summary: Converts pictures into ASCII art
  license: MIT
  license_family: MIT
  license_file: LICENCE
  # [sic] packaged from:
  # https://github.com/LeandroBarone/python-ascii_magic/blob/79c0cc6/LICENCE

extra:
  recipe-maintainers:
    - asford
