{% set name = "ascii_magic" %}
{% set version = "2.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ascii_magic-{{ version }}.tar.gz
  sha256: b26c417a4a672795522da289cdfc6de4d5303690ea2f4361ae5cf85b284732f8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - colorama
    - pillow
    - python >={{ python_min }}

test:
  imports:
    - ascii_magic
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/LeandroBarone/python-ascii_magic
  summary: Converts pictures into ASCII art
  license: MIT
  license_family: MIT
  license_file: LICENCE
  # [sic] packaged from:
  # https://github.com/LeandroBarone/python-ascii_magic/blob/79c0cc6/LICENCE

extra:
  recipe-maintainers:
    - asford
